### ISSUE TITLE
/32 is incorrectly stripped from IPv6 networks

### ISSUE THREAD

**Issue by LionelCons** [voxpupuli/puppet-ipset#30] opened 2020-03-30 11:49 UTC
`ipset_sync` incorrectly strips /32 from IPv6 networks (e.g. `fe80::/32`).

This happens here: https://github.com/voxpupuli/puppet-ipset/blob/master/files/ipset_sync#L77

`/32` should only be stripped if `family` is `inet`. Similarly, `/128` should only be stripped if `family` is `inet6` (but this is not a problem in practice).

**Comment by bastelfreak** [comment] 2020-10-07 07:36
hey @LionelCons, thanks for bringing this up. are you able to provide a PR for this?

**Comment by LionelCons** [comment] 2020-10-07 07:48
Sorry but I do not use `puppet-ipset` anymore.

**Comment by maxadamo** [comment] 2022-05-11 11:40
fixed by of #66 
duplicate of #65 
I wrongly open a new issue which is the same as this one. 
I close mine and I leave this one open, which is older.

**Closed** 2022-07-06 11:01 UTC
Labels: bug, needs-tests, needs-work
